name: Deployment workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Testing server ssh connection
      uses: appleboy/ssh-action@master

      with:
        host: angron42.pp.ua
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd Telegram-status-collector
          git pull origin master
          cd client
          mv config.yml.example config.yml
          echo '${{ secrets.CLIENT_CONFIG }}' > config.yml
