name: Deployment workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master

      with:
        host: angron42.pp.ua
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Stop server
          screen -X -S Telegram-status-collector.client quit
          screen -X -S Telegram-status-collector.client.update-loop quit

          # Pull changes
          cd ~/Telegram-status-collector
          git pull origin master
          
          # Deploy telegram client
          echo '${{ secrets.CLIENT_CONFIG }}' > ~/Telegram-status-collector/client/config.yml
          
          pip install -r ~/Telegram-status-collector/client/requirements.txt
          python ~/Telegram-status-collector/client/tools/setup-db.py
          
          screen -S Telegram-status-collector.client -d -m python ~/Telegram-status-collector/client/main.py
          screen -S Telegram-status-collector.client.update-loop -d -m python ~/Telegram-status-collector/client/scripts/update_loop.py
