name: Deployment workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Testing server ssh connection
      uses: appleboy/ssh-action@master

      with:
        host: angron42.pp.ua
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Pull changes
          cd ~/Telegram-status-collector
          git pull origin master
          
          # Deploy telegram client
          mv ./client/config.yml.example ./client/config.yml
          echo '${{ secrets.CLIENT_CONFIG }}' > ./client/config.yml
          
          pip install -r ./client/requirements.txt
          python ./client/tools/setup-db.py
          
          tmux new -d 'python ./client/scripts/update_loop.py'
          tmux new -d 'python ./client/main.py'
